### ISSUE TITLE
Peach collector is causing our app to crash

### ISSUE THREAD

**Issue by ptornhult** [ebu/peach-collector-android#6]
We're seeing crashes related to the Peach collector:
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
       at androidx.room.EntityDeletionOrUpdateAdapter.handle(EntityDeletionOrUpdateAdapter.java:70)
       at ch.ebu.peachcollector.EventDao_Impl.update(EventDao_Impl.java:206)
       at ch.ebu.peachcollector.PeachCollector$3.run(PeachCollector.java:221)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
       
This is on v1.0.10, Android 6.0.1, Lenovo TAB 10, Landscape mode

**Comment by lovacorp** [comment]
We are still seeing this crash in version 1.1.0.
